# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/updater"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/php-fpm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/updater"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/tor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
